CREATE TABLE IF NOT EXISTS `tbl_user` (
 `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'id',
 `name` varchar(128) NOT NULL default '' comment '姓名',
 `mobile` varchar(16) NOT NULL default '' comment '手机',
 `email` varchar(128) NOT NULL default '' comment '联系邮箱',
 `password` varchar(128) NOT NULL default '' comment '密码',
 `face` varchar(128) NOT NULL default '' comment '头像',
 `sex` tinyint(3) NOT NULL default 0 comment '性别',
 `desc` varchar(512) NOT NULL default '' comment '描述',
 `create_by` bigint(20) NOT NULL DEFAULT 0 COMMENT '创建人',
 `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
 `update_by` bigint(20) NOT NULL DEFAULT 0 COMMENT '更新人',
 `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
 `deleted` tinyint(3) NOT NULL DEFAULT 0 COMMENT '是否删除，0-正常 1-删除',
 PRIMARY KEY (`id`),
 key idx_mobile (mobile)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 auto_increment = 1000 COMMENT='用户';
CREATE TABLE IF NOT EXISTS `tbl_banner` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'id',
  `title` varchar(64) NOT NULL DEFAULT '' COMMENT '标题',
  `url` varchar(64) NOT NULL DEFAULT '' COMMENT '图片url',
  `link` varchar(64) NOT NULL DEFAULT '' COMMENT '链接',
  `background` varchar(32) NOT NULL DEFAULT '' COMMENT '背景',
  `sort` int(10) NOT NULL DEFAULT 0 COMMENT '顺序',
  `desc` varchar(512) NOT NULL default '' comment '描述',
  `deleted` tinyint(4) NOT NULL DEFAULT '0' COMMENT '0-正常，1-删除',
  `create_by` bigint(20) NOT NULL DEFAULT '0' COMMENT '创建人',
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` bigint(20) NOT NULL DEFAULT '0' COMMENT '更新人',
  `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8 COMMENT='banner';
CREATE TABLE IF NOT EXISTS `tbl_chinese_herb` (
 `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'id',
 `type` bigint(20) NOT NULL default 0 COMMENT '类型',
 `name` varchar(64) NOT NULL default '' comment '名称',
 `en_name` varchar(64) NOT NULL default '' comment '英文名',
 `alias` varchar(256) NOT NULL default '' comment '别名',
 `pic` varchar(128) NOT NULL default '' comment '图片',
 `zwxt` varchar(1024) NOT NULL default '' comment '植物形态',
 `yybw` varchar(1024) NOT NULL default '' comment '药用部位',
 `cdfb` varchar(1024) NOT NULL default '' comment '产地分布',
 `csjg` varchar(1024) NOT NULL default '' comment '采收加工',
 `ycxz` varchar(1024) NOT NULL default '' comment '药材性状',
 `xwgj` varchar(1024) NOT NULL default '' comment '性味归经',
 `gxzy` varchar(1024) NOT NULL default '' comment '功效与作用',
 `lcyy` varchar(1024) NOT NULL default '' comment '临床应用',
 `ylyj` varchar(1024) NOT NULL default '' comment '药理研究',
 `hxcf` varchar(1024) NOT NULL default '' comment '化学成分',
 `syjj` varchar(1024) NOT NULL default '' comment '使用禁忌',
 `create_by` bigint(20) NOT NULL DEFAULT 0 COMMENT '创建人',
 `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
 `update_by` bigint(20) NOT NULL DEFAULT 0 COMMENT '更新人',
 `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
 `deleted` tinyint(3) NOT NULL DEFAULT 0 COMMENT '是否删除，0-正常 1-删除',
 PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 auto_increment = 1000 COMMENT='中药';
CREATE TABLE IF NOT EXISTS `tbl_herb_pharmacy` (
 `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'id',
 `herb_id` bigint(20) NOT NULL default 0 COMMENT '中药',
 `content` varchar(1024) NOT NULL default '' comment '内容',
 `create_by` bigint(20) NOT NULL DEFAULT 0 COMMENT '创建人',
 `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
 `update_by` bigint(20) NOT NULL DEFAULT 0 COMMENT '更新人',
 `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
 `deleted` tinyint(3) NOT NULL DEFAULT 0 COMMENT '是否删除，0-正常 1-删除',
 PRIMARY KEY (`id`),
 key idx_herb_id(`herb_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 auto_increment = 1000 COMMENT='药方';
